### ISSUE TITLE
The App is not compatible with prestashop new version 1.7

### ISSUE THREAD

**Issue by bulunluo** [pintawebware/prestashop-mobile-admin#1]
The App is not compatible with prestashop new version 1.7.
It shows error:
JSON could not be serialized because of error: The data couldn't be read because it isn't in the correct format.

**Comment by bulunluo** [comment]
I tested with 1.6 version, it's fine.

**Comment by kirians** [comment]
Hi, can give test access, to see response, we check with 1.7

my email ruslan@pinta.com.ua

**Comment by Vrijlating** [comment]
Hello, i have also try to install it on PS 1.7 but give me a compatibility error

**Comment by AlekseyGromov** [comment]
Hello, Vrijlating!
Please, send screen of your error result.

Best regards,
PrestaShop Mobile Admin support Team

**Comment by bulunluo** [comment]
Hello
	I will send you soon when i am in the office.
	Thank U.

**Comment by AlekseyGromov** [comment]
Hello, Vrijlating!
Sure, we will wait!

Best regards,
PrestaShop Mobile Admin support Team

**Comment by ec1986** [comment]
Hi,

I'm also having trouble with Prestashop 1.7. 
What to do?

Best regards,
EC

**Comment by kirians** [comment]
Hi
write me in ruslan@pinta.com.ua
Best Regards
